### ISSUE TITLE
Why does the http://blog-example.meteor.com say "This site has crashed"?

### ISSUE THREAD

**Issue by tizol** [Differential/meteor-blog#194] opened 2015-07-06 04:39 UTC
![screen shot 2015-07-05 at 9 41 45 pm](https://cloud.githubusercontent.com/assets/6495684/8515791/b44d0a4a-235e-11e5-8460-5d1bccb64f6c.png)

**Comment by hellogerard** [comment] 2015-07-06 17:05
Dupe of #190.

**Closed by hellogerard** 2015-07-06 17:05 UTC
