### ISSUE TITLE
Error on fresh Instalation

### ISSUE THREAD

**Issue by cesarve77** [Differential/meteor-blog#217] opened 2015-10-07 03:18 UTC
when I run 
  $ meteor add ryw:blog
on complete new fresh installation of meteor i get
  Changes to your project's package version selections:                                          
  ryw:blog  added, version 0.5.1        // that is not the last version

if I run 
  $ meteor add ryw:blog@=0.7.1
I get

   => Errors while adding packages:             
                                              
  While selecting package versions:
  error: Conflict: Constraint less@1.0.5 is not satisfied by less 2.5.0_3.
  Constraints on package "less":
  * less@=2.5.0_3 <- top level
  * less@1.0.5 <- ryw:blog 0.7.1
  * less@1.0.11 <- lovetostrike:shareit 0.4.1 <- ryw:blog 0.7.1
  * less@2.5.0_1 <- gfk:notifications 1.1.4 <- ryw:blog 0.7.1

  Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_3.  
  Constraints on package "less":
  * less@=2.5.0_3 <- top level
  * less@1.0.5 <- ryw:blog 0.7.1
  * less@1.0.11 <- lovetostrike:shareit 0.4.1 <- ryw:blog 0.7.1
  * less@2.5.0_1 <- gfk:notifications 1.1.4 <- ryw:blog 0.7.1

**Comment by hellogerard** [comment] 2015-10-07 04:53
This is a meteor 1.2 compatible issue. Release is forthcoming. See #209. Dupe of #212.

**Closed by hellogerard** 2015-10-07 04:53 UTC
